version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SETUP_ENVINROMENT: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    volumes:
      - .:/app
      - /app/node_modules
    command: ["node", "server.js"]
